# Generated by Django 6.0.3 on 2026-08-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_customer_hub_customer_tracking_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='delivery_status',
            field=models.CharField(choices=[('At Hub', 'At Hub'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], default='At Hub', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
