# Generated by Django 6.0.3 on 2026-08-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customer_delivery_status_customer_item_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='item_description',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='quantity',
        ),
        migrations.AddField(
            model_name='parcel',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parcel',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
