# Generated by Django 6.0.3 on 2026-08-25 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_customer_item_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_parcels', to='core.customer'),
        ),
    ]
