# Generated by Django 6.0.3 on 2026-08-25 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_parcel_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='destination_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_parcels', to='core.hub'),
        ),
    ]
