# Generated by Django 6.0.3 on 2026-09-24 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_customer_deleted_at_parcel_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'hub')},
        ),
    ]
