# Generated by Django 6.0.3 on 2026-09-24 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_customer_phone_alter_customer_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'hub')},
        ),
        migrations.AlterField(
            model_name='customer',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('phone', 'hub'), ('tracking_id', 'hub')},
        ),
    ]
